version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: fraudguard-db
    environment:
      POSTGRES_USER: fraudguard
      POSTGRES_PASSWORD: fraudguard_secure_2024
      POSTGRES_DB: fraudguard_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fraudguard -d fraudguard_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fraudguard-network

  redis:
    image: redis:7-alpine
    container_name: fraudguard-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fraudguard-network

  prometheus:
    image: prom/prometheus:latest
    container_name: fraudguard-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - fraudguard-network

  grafana:
    image: grafana/grafana:latest
    container_name: fraudguard-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: fraudguard
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - fraudguard-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  fraudguard-network:
    driver: bridge
